parameters:
  poolImage: 'macOS-latest'
  targetOS: 'darwin'
  targetArch: 'amd64'
  dependStep: 'release_environment'
  relVersion: ''
jobs:
- job: build_${{ parameters.targetOS }}_${{ parameters.targetArch }}_actions
  dependsOn:
    ${{ parameters.dependStep }}
  variables:
    GOOS: ${{ parameters.targetOS }}
    GOARCH: ${{ parameters.targetArch }}
    REL_VERSION: ${{ parameters.relVersion }}
  pool:
    vmImage: '${{ parameters.poolImage }}'
  steps:
    - task: GoTool@0
      inputs:
        version: '1.12'
    - task: Bash@3
      displayName: 'Set up the Go workspace'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p '$(GOPATH)/pkg'
          mkdir -p '$(GOPATH)/bin'
          mkdir -p '$(modulePath)'
          shopt -s extglob
          mv !(gopath) '$(modulePath)'
          echo '##vso[task.prependpath]$(GOBIN)'
    - task: Bash@3
      displayName: 'Install dep'
      inputs:
        targetType: 'inline'
        script: |
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
    - task: CmdLine@2
      displayName: 'Run make deps'
      inputs:
        script: 'make deps'
        workingDirectory: '$(modulePath)'
        failOnStderr: true
    - task: CmdLine@2
      displayName: 'Run make test'
      condition: ne('${{ parameters.targetArch }}', 'arm')
      inputs:
        script: 'make test'
        workingDirectory: '$(modulePath)'
        failOnStderr: true
    - task: CmdLine@2
      displayName: 'Run make build'
      inputs:
        script: 'make build TARGETS=${{ parameters.targetOS }} ARCH=$(GOARCH)'
        workingDirectory: '$(modulePath)'
        failOnStderr: true
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/actions_${{ parameters.targetOS }}.zip'
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/actions_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)'
        ArtifactName: 'drop'
        publishLocation: 'Container'