//
//Copyright (c) 2024 Diagrid Inc.
//Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: proto/stored/leadership.proto

package stored

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Leadership is the message written to the leadership table when the replica
// gains ownership of the leader key.
type Leadership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// total is this replicas understanding of the total number of partition
	// replicas.
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// uid is a unique identifier for this replica. Ensures a single replica
	// is the leader for a given partition.
	Uid uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// replica_data is custom data that is associated with this leader (replica).
	// All leader data will be sent to library consumer on leadership table
	// updates.
	ReplicaData *anypb.Any `protobuf:"bytes,3,opt,name=replica_data,json=replicaData,proto3,oneof" json:"replica_data,omitempty"`
}

func (x *Leadership) Reset() {
	*x = Leadership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stored_leadership_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Leadership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leadership) ProtoMessage() {}

func (x *Leadership) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stored_leadership_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leadership.ProtoReflect.Descriptor instead.
func (*Leadership) Descriptor() ([]byte, []int) {
	return file_proto_stored_leadership_proto_rawDescGZIP(), []int{0}
}

func (x *Leadership) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Leadership) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Leadership) GetReplicaData() *anypb.Any {
	if x != nil {
		return x.ReplicaData
	}
	return nil
}

var File_proto_stored_leadership_proto protoreflect.FileDescriptor

var file_proto_stored_leadership_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x2f, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x3c,
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x42, 0x37, 0x5a,
	0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x61, 0x67,
	0x72, 0x69, 0x64, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x74, 0x63, 0x64, 0x2d, 0x63, 0x72,
	0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_stored_leadership_proto_rawDescOnce sync.Once
	file_proto_stored_leadership_proto_rawDescData = file_proto_stored_leadership_proto_rawDesc
)

func file_proto_stored_leadership_proto_rawDescGZIP() []byte {
	file_proto_stored_leadership_proto_rawDescOnce.Do(func() {
		file_proto_stored_leadership_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stored_leadership_proto_rawDescData)
	})
	return file_proto_stored_leadership_proto_rawDescData
}

var file_proto_stored_leadership_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_stored_leadership_proto_goTypes = []interface{}{
	(*Leadership)(nil), // 0: cron.stored.Leadership
	(*anypb.Any)(nil),  // 1: google.protobuf.Any
}
var file_proto_stored_leadership_proto_depIdxs = []int32{
	1, // 0: cron.stored.Leadership.replica_data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stored_leadership_proto_init() }
func file_proto_stored_leadership_proto_init() {
	if File_proto_stored_leadership_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stored_leadership_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Leadership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_stored_leadership_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stored_leadership_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stored_leadership_proto_goTypes,
		DependencyIndexes: file_proto_stored_leadership_proto_depIdxs,
		MessageInfos:      file_proto_stored_leadership_proto_msgTypes,
	}.Build()
	File_proto_stored_leadership_proto = out.File
	file_proto_stored_leadership_proto_rawDesc = nil
	file_proto_stored_leadership_proto_goTypes = nil
	file_proto_stored_leadership_proto_depIdxs = nil
}
