name: Release Docker Container
on:
  workflow_dispatch:
  release:
    types: ["published"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_ID }}/cli:latest , ${{ secrets.DOCKER_REGISTRY_ID }}/cli:${{ github.event.release.name }}
          file: docker/Dockerfile
          build-args: |
            VERSION=${{ github.event.release.name }}
