name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "dev-container-feature/**"
      - .github/workflows/dev_container_feature**
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./dev-container-feature/src"