# ------------------------------------------------------------
# Copyright 2021 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------

# Runs the Dapr Windows Powershell Install Script

name: Run Dapr Windows Install Script

on:
  push:
    branches: [ master ]
    paths:
      - 'install/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'install/**'
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Dapr
      - name: Install DAPR CLI
        run: powershell "install/install.ps1"
      
      - name: Verify installed CLI version
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            $Env:Path += ";$Env:SystemDrive\dapr"
            $output=dapr --version
            $runtimeVerified = False
            $cliVerified = False
            for($i=0;$i-le $output.length-1;$i++)
            {
                if ($output[$i] -eq "Runtime version: n/a")
                {
                    $runtimeVerified = True
                }
                if ($output[$i] -match "CLI version: ")
                {
                    if ($output[$i].split(" ")[2] -ne "n/a")
                    {
                        $cliVerified = True
                    }
                }
            }
            if ($cliVerified && $runtimeVerified)
            {
                Write-Output "DAPR is installed and verified.";
                exit 0
            } else {
                exit 1
            }
